import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "../store/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OlaAuth Firebase",
  description: "Generated by create next app",
  themeColor: "#000000",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className} h-full bg-black`}>
      <body className="w-full">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
